### ISSUE TITLE
Android 6: setPreviewTexture failed

### ISSUE THREAD

**Issue by anjawahl** [LivotovLabs/CamView#36]
Getting "setPreviewTexture failed"-Error on Nexus 7 with Android 6. 
It's working without errors on all my other test devices.
Scanner is working nevertheless!

E/ScannerLiveView: setPreviewTexture failed
                    java.io.IOException: setPreviewTexture failed
                        at android.hardware.Camera.setPreviewSurface(Native Method)
                        at android.hardware.Camera.setPreviewDisplay(Camera.java:629)
                        at eu.livotov.labs.android.camview.camera.v1.DefaultCameraV1Controller.startPreview(DefaultCameraV1Controller.java:136)
                        at eu.livotov.labs.android.camview.CameraLiveView.setCamera(CameraLiveView.java:186)
                        at eu.livotov.labs.android.camview.CameraLiveView$1.onOperationCompleted(CameraLiveView.java:115)
                        at eu.livotov.labs.android.camview.camera.v1.DefaultCameraV1Controller$5.onPostExecute(DefaultCameraV1Controller.java:328)
                        at eu.livotov.labs.android.camview.camera.CAMViewAsyncTask$Handler.handleMessage(CAMViewAsyncTask.java:231)
                        at android.os.Handler.dispatchMessage(Handler.java:102)
                        at android.os.Looper.loop(Looper.java:148)
                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                        at java.lang.reflect.Method.invoke(Native Method)
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/Camera: Error 2

**Comment by livotov** [comment]
Just got the N7 device, let me try and I'll see if I can fix that
