### ISSUE TITLE
Error by loading parameters

### ISSUE THREAD

**Issue by Seroga88i** [LivotovLabs/CamView#58]
When I start my activity with a scannerView I get this error but only on an OnePlus One:
`E/DefaultCameraV1Controller: Master parameters set was rejected by a camera, trying failsafe one.
                                                                                      java.lang.RuntimeException: getParameters failed (empty parameters)
                                                                                          at android.hardware.Camera.native_getParameters(Native Method)
                                                                                          at android.hardware.Camera.getParameters(Camera.java:1965)
                                                                                          at eu.livotov.labs.android.camview.camera.v1.CameraUtilsV1.getMainCameraParameters(CameraUtilsV1.java:42)
                                                                                          at eu.livotov.labs.android.camview.camera.v1.DefaultCameraV1Controller.startPreview(DefaultCameraV1Controller.java:106)
                                                                                          at eu.livotov.labs.android.camview.CameraLiveView.setCamera(CameraLiveView.java:205)
                                                                                          at eu.livotov.labs.android.camview.CameraLiveView$1.onOperationCompleted(CameraLiveView.java:134)
                                                                                          at eu.livotov.labs.android.camview.camera.v1.DefaultCameraV1Controller$5.onPostExecute(DefaultCameraV1Controller.java:308)
                                                                                          at eu.livotov.labs.android.camview.camera.CAMViewAsyncTask$Handler.handleMessage(CAMViewAsyncTask.java:231)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5466)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/DefaultCameraV1Controller: Failsafe parameters set was rejected by a camera, trying to use it as is.
                                                                                      java.lang.RuntimeException: getParameters failed (empty parameters)
                                                                                          at android.hardware.Camera.native_getParameters(Native Method)
                                                                                          at android.hardware.Camera.getParameters(Camera.java:1965)
                                                                                          at eu.livotov.labs.android.camview.camera.v1.CameraUtilsV1.getFailsafeCameraParameters(CameraUtilsV1.java:137)
                                                                                          at eu.livotov.labs.android.camview.camera.v1.DefaultCameraV1Controller.startPreview(DefaultCameraV1Controller.java:116)
                                                                                          at eu.livotov.labs.android.camview.CameraLiveView.setCamera(CameraLiveView.java:205)
                                                                                          at eu.livotov.labs.android.camview.CameraLiveView$1.onOperationCompleted(CameraLiveView.java:134)
                                                                                          at eu.livotov.labs.android.camview.camera.v1.DefaultCameraV1Controller$5.onPostExecute(DefaultCameraV1Controller.java:308)
                                                                                          at eu.livotov.labs.android.camview.camera.CAMViewAsyncTask$Handler.handleMessage(CAMViewAsyncTask.java:231)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5466)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 E/ScannerLiveView: setPreviewTexture failed
                                                                            java.io.IOException: setPreviewTexture failed
                                                                                at android.hardware.Camera.setPreviewSurface(Native Method)
                                                                                at android.hardware.Camera.setPreviewDisplay(Camera.java:652)
                                                                                at eu.livotov.labs.android.camview.camera.v1.DefaultCameraV1Controller.startPreview(DefaultCameraV1Controller.java:129)
                                                                                at eu.livotov.labs.android.camview.CameraLiveView.setCamera(CameraLiveView.java:205)
                                                                                at eu.livotov.labs.android.camview.CameraLiveView$1.onOperationCompleted(CameraLiveView.java:134)
                                                                                at eu.livotov.labs.android.camview.camera.v1.DefaultCameraV1Controller$5.onPostExecute(DefaultCameraV1Controller.java:308)
                                                                                at eu.livotov.labs.android.camview.camera.CAMViewAsyncTask$Handler.handleMessage(CAMViewAsyncTask.java:231)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5466)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Do you have some ideas how to fix this issue?

**Comment by rohannexialabs** [comment]
I am getting same issue, any idea on how to fix this?
